name: Composer repository

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Private Composer Registry
        uses: djsutter/satis-build@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # App/OAuth token, PAT
          satis_config: satis.json
          output: repository
      - env:
          GIT_EMAIL: bot@github.com
          GIT_NAME: cool-bot
        run: |
          git config user.name $GIT_NAME
          git config user.email $GIT_EMAIL
          git add repository/
          git commit -m "Re-built repository assets"
          git push
