name: Composer repository

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Private Composer Registry
        uses: pco-bcp/satis-build@v2
        with:
          token: ${{ secrets.APP_PAT }} # App/OAuth token, PAT
      - env:
          GIT_EMAIL: bot@github.com
          GIT_NAME: cool-bot
        run: |
          git config user.name $GIT_NAME
          git config user.email $GIT_EMAIL
          git add repository/
          git commit -m "Re-built repository assets"
          git push
